print(2 + 3)
print(3 - 1)
print(2 * 3)
print(3 / 2)
print(3 ** 2)
print(3 % 2)
print(3 // 2)

#Checking data types 

print(type(10))
print(type(3.14))
print(type(1 + 3j))
print(type('Asabeneh'))
print(type([1, 2, 3]))
print(type({'name':'Asabeneh'})) 
print(type({9.8, 3.14, 2.7}))    
print(type((9.8, 3.14, 2.7))) 

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4 - 4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type('Your name'))
print(type('Your family name Your name'))
print(type('Your name'))
print(type('Your country'))